### ISSUE TITLE
error

### ISSUE THREAD

**Issue by LXWDL** [Shirhe-Lyh/slim_cnn_test#1]
Hi,thanks for your shares,but  I encountered the following error：
Traceback (most recent call last):
  File "export_inference_graph.py", line 64, in <module>
    tf.app.flags.mark_flag_as_required('trained_checkpoint_prefix')
AttributeError: module 'tensorflow.python.platform.flags' has no attribute 'mark_flag_as_required'

**Comment by Shirhe-Lyh** [comment]
@LXWDL 感谢你的访问和反馈！这个错误应该是 tensorflow 的版本问题，你升级一下 tensorflow 或者最简单的将报错的两行（64/65 行）注释掉就可以了。

**Comment by 13293824182** [comment]
Hi,thanks for your shares,but I encountered the following error：
Traceback (most recent call last):
  File "train.py", line 131, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 90, in main
    cls_model = model.Model(is_training=True, num_classes=10)
AttributeError: module 'model' has no attribute 'Model'

**Comment by Shirhe-Lyh** [comment]
@13293824182 Hi, thanks!
In the file model.py, we define a class Model, and the sentence:
cls_model = model.Model(is_training=True, num_classes=10)
is meaning that we specify an instance of the class Model, so are you rename the class Model?

**Comment by 13293824182** [comment]
No. I used your code directly, then changed the data path to my actual path and got this error.  Thank you for your help

**Comment by 13293824182** [comment]
python3 train.py \ --record_path ./datasets/train.record \ --logdir ./training/                          18-05-28 14:05
Traceback (most recent call last):
  File "train.py", line 102, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 77, in main
    data_provider = slim.dataset_data_provider.DatasetDataProvider(dataset)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/slim/python/slim/data/dataset_data_provider.py", line 94, in __init__
    scope=scope)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/slim/python/slim/data/parallel_reader.py", line 238, in parallel_read
    data_files = get_data_files(data_sources)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/slim/python/slim/data/parallel_reader.py", line 306, in get_data_files
    if '*' in data_sources or '?' in data_sources or '[' in data_sources:
TypeError: argument of type 'NoneType' is not iterable

**Comment by 13293824182** [comment]
2018-05-28 15:38:35.233011: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)

**Comment by Shirhe-Lyh** [comment]
@13293824182 这不是错误，是已经在训练了，你需要通过 tensorboard 观察训练损失。
